apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hivebox-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - hivebox
  selector:
    matchLabels:
      app: hivebox
  endpoints:
    - port: http
      path: /metrics
      interval: 30s