apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivebox
  namespace: hivebox
spec:
  template:
    spec:
      containers:
        - name: hivebox
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "1Gi"