apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hivebox

commonLabels:
  app.kubernetes.io/name: minio
  app.kubernetes.io/component: storage
  app.kubernetes.io/part-of: hivebox

resources:
  - minio-deployment.yaml
  - minio-service.yaml
