apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hivebox

commonLabels:
  app.kubernetes.io/name: valkey
  app.kubernetes.io/component: cache
  app.kubernetes.io/part-of: hivebox

resources:
  - valkey-deployment.yaml
  - valkey-service.yaml

images:
  - name: valkey/valkey
    newName: valkey/valkey
    newTag: 8.0.1-alpine