apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hivebox

resources:
  - ../../base
  - ../../infrastructure/valkey
  - ../../infrastructure/minio

patches:
  - path: patches/replicas.yaml
  - path: patches/resources.yaml
  - path: patches/configmap.yaml

labels:
  - pairs:
      env: stg